#name: Docker Build and Push
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Docker Build
#        uses: docker/setup-buildx-action@v1
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build Docker image
#        run: |
#          docker build -t s24916/s24916_flask_app:latest .
#          docker tag s24916/s24916_flask_app:latest s24916/s24916_flask_app:${{ github.sha }}
#
#      - name: Push to Docker Hub
#        run: |
#          docker push s24916/s24916_flask_app:latest
#          docker push s24916/s24916_flask_app:${{ github.sha }}
